name: RSpec and RuboCop

on:
  push:
    branches-ignore:
      - master

jobs:
  rspec:
    runs-on: ubuntu-latest

    services:
      postgres:
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        image: postgres:12.3
        options: --health-cmd pg_isready --health-interval 10s --health-retries 5 --health-timeout 5s
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          path: vendor/bundle
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.3

      - run: gem install bundler
      - run: bundle install --path vendor/bundle
      - run: RAILS_ENV=test bin/rails db:prepare
      - run: bin/rspec

  rubocop:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          path: vendor/bundle
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.3

      - run: gem install bundler
      - run: bundle install --path vendor/bundle
      - run: bin/rubocop --parallel